language: java
jdk:
  - oraclejdk7
before_script:
  - sudo apt-get install subversion
  - svn -h
  - sudo apt-get install ftp
  - ftp -h
  - sudo apt-get install ssh
script:
  - cd api
  - mvn install
  - cd ../web
  - mvn package
  - cd target
  - ls -al
  - scp web.war ainia@182.18.31.105:web.war <<< EOF
  - ppainia
