language: java
jdk:
  - oraclejdk7
before_script:
  - sudo apt-get install subversion
  - svn -h
script:
  - cd api
  - mvn install
  - cd ../web
  - mvn package
  - svn checkout https://svn.sinaapp.com/ecgtest/1 target --username cloverren@163.com --password cloverren --no-auth-cache
  - cd target
  - svn delete ecgtest.war
  - svn commit -m "delete old war" --username cloverren@163.com --password cloverren --no-auth-cache
  - mv -f web.war ecgtest.war
  - svn add ecgtest.war
  - svn commit -m "upload new war" --username cloverren@163.com --password cloverren --no-auth-cache