language: java
jdk:
  - oraclejdk7
env:
  global:
    - TIMEOUT=600000
before_script:
  - sudo apt-get install subversion
  - svn -h
script: 
  - mvn package
  - svn checkout https://svn.sinaapp.com/ecgtest/1 sae--username cloverren@163.com --password cloverren --no-auth-cache
  - cd sae
  - svn delete ecgtest.war
  - svn commit -m "delete old war" --username cloverren@163.com --password cloverren --no-auth-cache
  - mv -f ../ecg-1.0.0-SNAPSHOT.war ecgtest.war
  - svn add ecgtest.war
  - svn commit -m "upload new war" --username cloverren@163.com --password cloverren --no-auth-cache